### PR TITLE
fix: preserve retro compatibility of claim events indexing

### LINKED ISSUE #1433: [BUG] handle aggkit to be backward compatible
aggkit with v0.8.0-beta4 is not backward compatible with older agglayer contracts version
we need to make changed in syncer so that it is backward compatible and also forward compatible so that once we have the new events coming in, we sync only new events and skip old events

### PR DESCRIPTION
**Pull request by Stefan-Ethernal**
## 🔄 Changes Summary
Make indexing of claim events backward compatible in a way that even for the sovereign chain deployments (namely the one which deploy the `AgglayerBridgeL2`), we still index the `ClaimEvent` as well. On the first occurrence of `DetailedClaimEvent`, we inhibit the further processing of the (legacy) `ClaimEvent`.

### Additional changes
- correct the error message if querying of `lastDepositCount` on the `AgglayerBridge` contract fails
- fix make lint target, so that it uses the golangci-lint-v2, since we are running the configuration for the `golangci-lint-v2`. This change also requires `golangci-lint-v2` to be installed in the `GOPATH`

## ⚠️ Breaking Changes
N/A

## 📋 Config Updates
N/A

## ✅ Testing
- 🤖 **Automatic**: [Optional: Enumerate E2E tests]
- 🖱️ **Manual**: [Optional: Steps to verify]

## 🐞 Issues
- Closes #1433

### CODE REVIEW

File: bridgesync/migrations/bridgesync0012.sql [hunk 1]
```diff
@@ -0,0 +1,5 @@
+-- +migrate Down
+ALTER TABLE claim DROP COLUMN source;
```
Comment (goran-ethernal) [inline bridgesync/migrations/bridgesync0012.sql]: Maybe call it `type`?

File: bridgesync/downloader.go [hunk 2]
```diff
@@ -106,9 +107,13 @@ func buildAppender(
 	switch bridgeDeployment.kind {
 	case NonSovereignChain:
 		appender[claimEventSignature] = buildClaimEventHandler(
-			bridgeDeployment.agglayerBridge, client, bridgeAddr, syncFullClaims, logger)
+			bridgeDeployment.agglayerBridge, client, querier,
```
Comment (temaniarpit27) [inline bridgesync/downloader.go]: nit: maybe extract both appender, NonSovereignChain can be empty

File: bridgesync/downloader.go [hunk 3]
```diff
@@ -383,10 +388,26 @@ func buildBridgeEventHandler(
...
+		// check if we already have passed the block which started indexing DetailedClaimEvent
+		existingClaims, _, err := querier.GetClaimsPaged(context.Background(), 1, 1, nil, nil)
+		if err != nil {
+			return fmt.Errorf("error querying existing claims: %w", err)
+		}
+
+		if len(existingClaims) > 0 {
+			claim := existingClaims[0]
+			if claim.Type == DetailedClaimEvent {
+				logger.Debugf(
```
Comment (temaniarpit27) [inline bridgesync/downloader.go]: maybe we can store the claim in memory and we dont need to query everytime
and instead of querying the way we are doing above, we can search in whole table if any claim with `detailedclaimevent` type exist, so restarts are also taken care of
wdyt?

File: bridgesync/migrations/bridgesync0012.sql (hunk 1 above)
Comment (Stefan-Ethernal) [reply bridgesync/migrations/bridgesync0012.sql]: Fixed https://github.com/agglayer/aggkit/pull/1435/commits/1093adc4b5fdb1a45aa89dc1a62b2130f1288315

File: bridgesync/downloader.go (hunk 2 above)
Comment (Stefan-Ethernal) [reply bridgesync/downloader.go]: Fixed https://github.com/agglayer/aggkit/pull/1435/commits/25ebf77fdde415d758b773e48186f22d9ac1e43e

File: bridgesync/downloader.go (hunk 3 above)
Comment (Stefan-Ethernal) [reply bridgesync/downloader.go]: I have decided to proceed with the approach of querying the database and keep the logic as simple is possible. The reasoning behind it is that `buildAppender` (and downstream functions) are just helper functions, so it is not straight forward deciding where such cached object should belong (not to mention reorg logic and invalidating it if necessary etc). 

The query is simple and lightweight enough and is ran against indexed columns, so IMO performance shouldn't be an issue.

Please, lmk if you think otherwise, and we'll figure out how to address it.
https://github.com/agglayer/aggkit/pull/1435/commits/c7c4af3963d359284cf2dc1bbb2826cd258a592b

Comment (temaniarpit27) [reply bridgesync/downloader.go]: no worries, we can add optimization later if needed

**Review by temaniarpit27 — APPROVED** [review]

File: bridgesync/bridgesync.go [hunk 4]
```diff
@@ -297,7 +297,7 @@ func resolveBridgeDeployment(ctx context.Context,
 			agglayerBridgeL2: agglayerBridgeL2,
 		}, nil
 	} else if !strings.Contains(err.Error(), gethvm.ErrExecutionReverted.Error()) {
-		return nil, fmt.Errorf("unexpected error querying AgglayerBridge.BRIDGE_VERSION: %w", err)
+		return nil, fmt.Errorf("unexpected error querying AgglayerBridge.lastUpdatedDepositCount: %w", err)
```
[the remark this answers is not in the document]
Comment (Stefan-Ethernal) [reply bridgesync/bridgesync.go:300]: The change is documented in the PR description.

File: .github/test_e2e_op_args_base.json [hunk 5]
```diff
@@ -10,7 +10,7 @@
     "agg_sender_multisig_threshold": 2,
     "agg_sender_validator_total_number": 3,
     "log_level": "debug",
-    "additional_services": [],
+    "additional_services": [ ],
```
[the remark this answers is not in the document]
Comment (Stefan-Ethernal) [reply .github/test_e2e_op_args_base.json]: Change is reverted.

File: .github/test_e2e_cdk_erigon_args_base.json [hunk 6]
```diff
@@ -22,6 +22,6 @@
     "enable_normalcy": true,
     "erigon_strict_mode": false,
     "gas_token_enabled": false,
-    "additional_services": []
+    "additional_services": [ ]
```
[the remark this answers is not in the document]
Comment (Stefan-Ethernal) [reply .github/test_e2e_cdk_erigon_args_base.json]: Change is reverted.

File: bridgesync/migrations/bridgesync0012.sql [hunk 7]
```diff
@@ -0,0 +1,11 @@
+-- +migrate Down
+DROP INDEX IF EXISTS idx_claim_type_block;
+
+ALTER TABLE claim
+DROP COLUMN type;
+
+-- +migrate Up
+ALTER TABLE claim
+ADD COLUMN type TEXT NOT NULL DEFAULT '';
+
```
[the remark this answers is not in the document]
Comment (Stefan-Ethernal) [reply bridgesync/migrations/bridgesync0012.sql:12]: It is fine, once the version with this change is deployed, we are moving forward and start populating the `type` column. Note that it is expected that we move from `ClaimEvent` to `DetailedClaimEvent` and once it is done, we shouldn't go back to `ClaimEvent` ever again.

File: bridgesync/downloader.go [hunk 8]
```diff
@@ -383,10 +382,24 @@ func buildBridgeEventHandler(
...
 // buildClaimEventHandler creates a handler for the Claim event log.
 func buildClaimEventHandler(agglayerBridge *agglayerbridge.Agglayerbridge,
-	client aggkittypes.EthClienter, bridgeAddr common.Address, syncFullClaims bool,
-	logger *logger.Logger,
+	client aggkittypes.EthClienter, querier BridgeQuerier, bridgeAddr common.Address,
+	syncFullClaims bool, logger *logger.Logger,
 ) func(*sync.EVMBlock, types.Log) error {
 	return func(b *sync.EVMBlock, l types.Log) error {
+		// check if we already have passed the block which started indexing DetailedClaimEvent
+		boundaryBlock, err := querier.GetBoundaryBlockForClaimType(context.Background(), DetailedClaimEvent)
```
[the remark this answers is not in the document]
Comment (Stefan-Ethernal) [reply bridgesync/downloader.go]: Fixed https://github.com/agglayer/aggkit/pull/1435/commits/607c3ff54813ee1137b0f27ec85e7d7612f3711e

File: Makefile [hunk 9]
```diff
@@ -98,7 +98,7 @@ test-unit: ## Runs the unit tests
 
 .PHONY: lint
 lint: ## Runs the linter
-	export "GOROOT=$$(go env GOROOT)" && $$(go env GOPATH)/bin/golangci-lint run --timeout 5m
+	export "GOROOT=$$(go env GOROOT)" && $$(go env GOPATH)/bin/golangci-lint-v2 run --timeout 5m
```
[the remark this answers is not in the document]
Comment (Stefan-Ethernal) [reply Makefile:101]: Although it is unrelated, it caused some issues on my end, because of mismatch of golangci-lint tools. Therefore I have decided to change this. The change is documented in the PR desc.

File: bridgesync/migrations/bridgesync0012.sql [hunk 10]
```diff
@@ -1,6 +1,15 @@
 -- +migrate Down
+DROP INDEX IF EXISTS idx_claim_type_block;
+
+ALTER TABLE claim DROP COLUMN type;
+
+ALTER TABLE bridge DROP COLUMN to_address;
```
Comment (goran-ethernal) [inline bridgesync/migrations/bridgesync0012.sql:6]: This line is a duplicate.

**Review by goran-ethernal — APPROVED** [review]

File: bridgesync/migrations/bridgesync0012.sql (hunk 10 above)
Comment (Stefan-Ethernal) [reply bridgesync/migrations/bridgesync0012.sql:6]: Thanks, fixed https://github.com/agglayer/aggkit/pull/1435/commits/53623a5ed41cf80aa657ac91111a8c02225e706c
