### PR TITLE
fix: multiline swagger descriptions

### LINKED ISSUE #622: Fix multiline swagger descriptions

### PR DESCRIPTION
**Pull request by Stefan-Ethernal**
## Description

Fix the multiline comments in the Swagger docs for Bridge service. In cases there were multiple lines, only first one was rendered.

Fixes #622

### CODE REVIEW

File: bridgeservice/docs/docs.go [hunk 1]
```diff
@@ -125,7 +125,7 @@ const docTemplate = `{
         },
         "/claim-proof": {
             "get": {
-                "description": "Returns the Merkle proofs (local and rollup exit root) and",
+                "description": "Returns the Merkle proofs (local and rollup exit root) and\nthe corresponding L1 info tree leaf needed to verify a claim.",
```
Comment (temaniarpit27) [inline bridgeservice/docs/docs.go:128]: is there some automated way of multiline instead of putting `/n`?

Comment (Stefan-Ethernal) [reply bridgeservice/docs/docs.go:128]: Well, this is what swaggo generated. FWIW, it is rendered properly now. 

image

Seems that the common approach is to have a one liner description, but then linter complains about line being too long...

**Review by temaniarpit27 — APPROVED** [review]
💯

**Review by rachit77 — APPROVED** [review]
