### PR TITLE
fix: handle block range too large rpc error, and do chunk calls

### LINKED ISSUE #1386: [BUG] Error getting unset claims for block range: block range too large, max range: 1000
Image

### PR DESCRIPTION
**Pull request by goran-ethernal**
## 🔄 Changes Summary
This PR addresses the issue that happened on one of the testnets, which reported `block range too large` error when reading a contract for specific logs in a block range.

The PR adds a generic way to recognize the given error when reading contracts and does a chunk calls to get all the data to avoid the error.

## ⚠️ Breaking Changes
NA

## 📋 Config Updates
NA

## ✅ Testing
- 🤖 **Automatic**: `aggkit` CI

## 🐞 Issues
- Closes #1386

### CODE REVIEW

File: common/errors.go [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+
+import (
+	"errors"
+	"regexp"
+	"strings"
+)
+
+const maxRangeMatchGroups = 2
+
+// parseMaxRangeFromError extracts the max range value from error message
```
[the remark this answers is not in the document]
Comment (goran-ethernal) [reply common/errors.go]: Fix: https://github.com/agglayer/aggkit/pull/1387/commits/3ace366cb99bf29f90b0b7c3395f7ebd6b9a75db

File: common/errors.go [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+const maxRangeMatchGroups = 2
+
+// ParseMaxRangeFromError extracts the max range value from error message
+// Expected format: "block range too large, max range: 1000"
+func ParseMaxRangeFromError(errMsg string) (uint64, error) {
+	if !strings.Contains(errMsg, "block range too large") {
+		return 0, errors.New("not a block range error")
+	}
+
+	re := regexp.MustCompile(`max range:\s*(\d+)`)
```
Comment (Stefan-Ethernal) [inline common/errors.go]: consider extracting this to a package lvl variable (called e.g. `maxRangeRegExp`), in order to be executed only once. WDYT?

**Review by Stefan-Ethernal — APPROVED** [review]
:100: Nice

File: common/errors.go [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+	"errors"
+	"regexp"
+	"strings"
+)
+
+const maxRangeMatchGroups = 2
+
+// ParseMaxRangeFromError extracts the max range value from error message
+// Expected format: "block range too large, max range: 1000"
+func ParseMaxRangeFromError(errMsg string) (uint64, error) {
```
Comment (joanestebanr) [inline common/errors.go]: Maybe make more sense to return an bool instead an error: 
if true -> is a MaxRangeError and returns the max range

WDYT?

**Review by joanestebanr — APPROVED** [review]

File: common/errors.go (hunk 3 above)
Comment (goran-ethernal) [reply common/errors.go]: Fix: https://github.com/agglayer/aggkit/pull/1387/commits/a5e732c877746ca7f0bca34c3354fe2d8b577b7e

File: common/errors.go (hunk 2 above)
Comment (goran-ethernal) [reply common/errors.go]: Fix: https://github.com/agglayer/aggkit/pull/1387/commits/a5e732c877746ca7f0bca34c3354fe2d8b577b7e
