### PR TITLE
fix: bridge service db issues

### LINKED ISSUE #825: [BUG] Fix bridge service db bugs
# Bug Report

https://app.datadoghq.eu/logs?query=service%3Aaggkit%20network%3Acdk22%20-status%3A%28info%20OR%20error%29&agg_m=count&agg_m_source=base&agg_q=status%2Cservice&agg_q_source=base%2Cbase&agg_t=count&clustering_pattern_field_path=message&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&sort_m=%2C&sort_m_source=%2C&sort_t=%2C&storage=hot&stream_sort=time%2Cdesc&top_n=10%2C10&top_o=top%2Ctop&viz=pattern&x_missing=true%2Ctrue&from_ts=1754312786660&to_ts=1754399186660&live=true

## Description

DB issues and warnings

```
sql: Rows are closed
database is locked
context deadline exceeded
sql: transaction has already been committed or rolled back
```

### PR DESCRIPTION
**Pull request by rachit77**
## 🔄 Changes Summary
- This PR fixes the error we were noticing on bridge service `cdk22`

## 🐞 Issues
- Closes #825

### CODE REVIEW

**Review by temaniarpit27 — APPROVED** [review]

File: db/sqlite.go [hunk 1]
```diff
@@ -21,7 +21,10 @@ var (
 
 // NewSQLiteDB creates a new SQLite DB
 func NewSQLiteDB(dbPath string) (*sql.DB, error) {
-	return sql.Open("sqlite3", fmt.Sprintf("file:%s?_txlock=exclusive&_foreign_keys=on&_journal_mode=WAL", dbPath))
+	return sql.Open("sqlite3", fmt.Sprintf(
+		"file:%s?_txlock=immediate&_foreign_keys=on&_journal_mode=WAL&_busy_timeout=30000",
```
Comment (Stefan-Ethernal) [inline db/sqlite.go:25]: Is this busy timeout nominated in seconds? What does it denote and is this value too large maybe?

**Review by Stefan-Ethernal — APPROVED** [review]
💯

File: db/sqlite.go (hunk 1 above)
Comment (rachit77) [reply db/sqlite.go:25]: This tells SQLite if the database is locked (due to another transaction), wait up to 30 seconds before failing with a database is locked error. I have added this as a saftey net although in our write transaction this is not needed as we write transactions sequentially in the db.

`busy_timeout` value is specified in milliseconds
https://github.com/mattn/go-sqlite3#connection-string

**Review by vcastellm — APPROVED** [review]
