### PR TITLE
fix: set block timestamp and tx hash to pre-etrog claims

### LINKED ISSUE #995: pre-etrog claims don't have block timestamp and tx hashes set
Pre-Etrog claims don't have block timestamp and tx hashes set (http://34.89.33.65:5577/bridge/v1/claims?network_id=0&page_number=2935), the values are `0` and `0x0` respectively.

### PR DESCRIPTION
**Pull request by Stefan-Ethernal**
## 🔄 Changes Summary
- Notice that the claims that are done on the pre-Etrog bridge contracts, have the `block_timestamp` and `tx_hash` fields populated, which is not the case currently (http://34.89.33.65:5577/bridge/v1/claims?network_id=0&page_number=2935).

### :warning: Note
It is necessary to re-index the data, in order to have the `block_timestamp` and `tx_hash` data populated for pre-Etrog claims.

## ⚠️ Breaking Changes
- 🛠️ **Config**: N/A
- 🔌 **API/CLI**: N/A
- 🗑️ **Deprecated Features**: N/A

## 📋 Config Updates
- 🧾 **Diff/Config snippet**: N/A

## ✅ Testing
- 🤖 **Automatic**: N/A
- 🖱️ **Manual**:
1. Run the `aggkit` bridge service and index some bridge data for rollups that have been running prior to Etrog hardfork
2. Notice that the `tx_hash` and `block_timestamp` fields are set to non zero values

## 🐞 Issues
- Closes #995

### CODE REVIEW

**Review by joanestebanr — APPROVED** [review]

File: bridgesync/downloader.go [hunk 1]
```diff
@@ -146,14 +146,13 @@ func buildClaimEventHandler(contract *polygonzkevmbridgev2.Polygonzkevmbridgev2,
...
+			BlockTimestamp:     b.Timestamp,
+			TxHash:             l.TxHash,
 			GlobalIndex:        claimEvent.GlobalIndex,
 			OriginNetwork:      claimEvent.OriginNetwork,
 			OriginAddress:      claimEvent.OriginAddress,
 			DestinationAddress: claimEvent.DestinationAddress,
 			Amount:             claimEvent.Amount,
-			BlockTimestamp:     b.Timestamp,
-			TxHash:             l.TxHash,
-			FromAddress:        l.Address,
```
Comment (temaniarpit27) [inline bridgesync/downloader.go:156]: why did we remove this?

**Review by temaniarpit27 — DISMISSED** [review]

File: bridgesync/downloader.go (hunk 1 above)
Comment (Stefan-Ethernal) [reply bridgesync/downloader.go:156]: The `FromAddress` is set [here](https://github.com/agglayer/aggkit/blob/f8eb45673994c63e4b1c611d3e781c6411b2b702/bridgesync/processor.go#L256), in case full claims synchronization is enabled. It is misleading to set it to contract's address in case full claims sync is disabled. So IMO it is better to not set it, than set the misleading value.

Note that we are not setting [it](https://github.com/agglayer/aggkit/blob/f8eb45673994c63e4b1c611d3e781c6411b2b702/bridgesync/downloader.go#L146-L156) for Etrog claims either.

**Comment by temaniarpit27** [comment]
@Stefan-Ethernal will we do a resync after this change?

**Review by temaniarpit27 — APPROVED** [review]

**Comment by Stefan-Ethernal** [comment]
> @Stefan-Ethernal will we do a resync after this change?

Yep, the resync is required (and I've indicated this in the PR description). Rajesh communicated this to devtools.
