### PR TITLE
fix: make bridge exit limitation configurable

### LINKED ISSUE #618: Make PP certificate limitation for at least one bridge exit configurable
`Agglayer` introduced certificate height in the pessimistic proof program, so they do not require one bridge exit to be present in the PP certificate.

`Aggsender` should remove this limitation from its code as well, or at least make it configurable, where by default, this limitation should be turned off.

### PR DESCRIPTION
**Pull request by goran-ethernal**
### Description

`Agglayer` introduced certificate height in the pessimistic proof program, so they do not require one bridge exit to be present in the `PP` certificate.

This PR makes this limitation configurable on `Aggsender`, where it is turned off by default, meaning, PP certificate can be sent with only claims.

### Configuration Changes ⚙️
 - introduced `RequireOneBridgeInPPCertificate` `bool` field to the `aggsender` config which is a flag to force the `aggSender` to have at least one bridge exit in the `Pessimistic Proof` certificates. By default it is `true`.

Fixes #618

### CODE REVIEW

File: aggsender/flows/flow_pp.go [hunk 1]
```diff
@@ -45,17 +48,31 @@ func (p *PPFlow) CheckInitialStatus(ctx context.Context) error {
...
+		if errors.Is(err, errNoNewBlocks) {
+			// no new blocks to send a certificate,
 			// this is a valid case, so just return nil without error
 			return nil, nil
 		}
 
 		return nil, err
 	}
 
+	if p.forceOneBridgeExit && len(buildParams.Bridges) == 0 {
```
Comment (joanestebanr) [inline aggsender/flows/flow_pp.go]: you can use `buildParams.NumberOfBridges()` that prevent a nil pointer

File: aggsender/flows/flow_pp.go [hunk 2]
```diff
@@ -45,17 +48,31 @@ func (p *PPFlow) CheckInitialStatus(ctx context.Context) error {
...
+		// if forceOneBridgeExit is true, we need to ensure that there is at least one bridge exit
+		p.log.Infof("PPFlow - forceOneBridgeExit is true, but no bridges found, "+
+			"so no certificate will be built for range: %d - %d",
+			buildParams.FromBlock, buildParams.ToBlock)
+		return nil, nil
+	}
+
+	if len(buildParams.Bridges) == 0 && len(buildParams.Claims) == 0 {
```
Comment (joanestebanr) [inline aggsender/flows/flow_pp.go]: you can use `buildParams.IsEmpty()` that prevent a nil pointer

File: aggsender/config/config.go [hunk 3]
```diff
@@ -73,6 +73,9 @@ type Config struct {
 	RequireNoFEPBlockGap bool `mapstructure:"RequireNoFEPBlockGap"`
 	// OptimisticModeConfig is the configuration for optimistic mode (required by FEP mode)
 	OptimisticModeConfig optimistic.Config `mapstructure:"OptimisticModeConfig"`
+	// ForceOneBridgeExitForPP is a flag to force the AggSender to have at least one bridge exit
+	// for the Pessimistic Proof certificates
+	ForceOneBridgeExitForPP bool `mapstructure:"ForceOneBridgeExitForPP"`
```
Comment (joanestebanr) [inline aggsender/config/config.go]: Maybe the name is not clear enough... some ideas: 
- AllowPPCertificatesWithNoBridges
- PPCertifcateRequireMinimumOneBridge
- RequireOneBridgePerPPCertificate



Also, I think that it must be added to `docs/aggsender.md` BTW, I forget to add the optimistic ones

**Review by joanestebanr — APPROVED** [review]

File: aggsender/config/config.go (hunk 3 above)
Comment (goran-ethernal) [reply aggsender/config/config.go]: How about `RequireOneBridgeInPPCertificate`? WDYT?

File: aggsender/flows/flow_pp.go (hunk 2 above)
Comment (goran-ethernal) [reply aggsender/flows/flow_pp.go]: Fix: https://github.com/agglayer/aggkit/pull/619/commits/248abd6f3b477446df161e740ea42aa103c2a5e0

File: aggsender/flows/flow_pp.go (hunk 1 above)
Comment (goran-ethernal) [reply aggsender/flows/flow_pp.go]: Fix: https://github.com/agglayer/aggkit/pull/619/commits/248abd6f3b477446df161e740ea42aa103c2a5e0

File: aggsender/config/config.go (hunk 3 above)
Comment (goran-ethernal) [reply aggsender/config/config.go]: Fix: https://github.com/agglayer/aggkit/pull/619/commits/4613b93a77767f63d54b0e8eedbc0d8089347d79

I've updated the `aggsender.md`. Courtesy of the AI :wink:

**Review by temaniarpit27 — APPROVED** [review]
