### PR TITLE
fix: add lock to loadTrackedHeaders in reorg detector

### LINKED ISSUE #680: [BUG] subscriptions race condition in ReorgDetector at startup
add `rd.subscriptionsLock` [here](https://github.com/agglayer/aggkit/blob/develop/reorgdetector/reorgdetector.go#L263)

### PR DESCRIPTION
**Pull request by Stefan-Ethernal**
## Description

Fix race condition in loadTrackedHeaders in reorg detector on startup.
Also fix typo in function name.

Fixes #680 , #683

### CODE REVIEW

File: lastgersync/processor.go [hunk 1]
```diff
@@ -74,8 +74,10 @@ func (p *processor) ProcessBlock(ctx context.Context, block sync.Block) error {
 	if err != nil {
 		return fmt.Errorf("failed to start transaction: %w", err)
 	}
+
+	shouldRollback := true
 	defer func() {
-		if err != nil {
+		if shouldRollback {
```
Comment (temaniarpit27) [inline lastgersync/processor.go:80]: p.rollbackTransaction(tx)
similar func here?

**Review by temaniarpit27 — APPROVED** [review]
💯

File: lastgersync/processor.go (hunk 1 above)
Comment (Stefan-Ethernal) [reply lastgersync/processor.go:80]: Probably doesn't make sense at this point, because it is invoked only from a single place.

**Review by goran-ethernal — APPROVED** [review]

**Review by joanestebanr — APPROVED** [review]
