### PR TITLE
fix: replace ethClient.BlockByNumber by ethClient.HeaderByNumber

### LINKED ISSUE #1388: bug: some L2 report 'transaction type not supported`
# Bug Report

Bridgesyncer report `transaction type not supported` sycning from L2.

Log: 
```
FATAL	cmd/run.go:783	error creating bridgeSyncL2: failed to get initial block 32961352: transaction type not supported
```

Replacing [BlockByNumber](https://pkg.go.dev/github.com/ethereum/go-ethereum/ethclient#Client.BlockByNumber) by [HeaderByNumber](https://pkg.go.dev/github.com/ethereum/go-ethereum/ethclient#Client.HeaderByNumber) fix the issue

## Environment:
- Environment: `bali-63-outpost `
- Version: `v0.7.3`
## Additional context
* https://0xpolygon.slack.com/archives/C07HZQHN6RY/p1765204159899149 
* Thiago PR: 
    *   [https://github.com/agglayer/aggkit/compare/develop...tnobayashi/experiments#diff-c722091b8b989e579ab20f2c90135[…]665d207ee0aaaab182afff4524c829bR340](https://github.com/agglayer/aggkit/compare/develop...tnobayashi/experiments#diff-c722091b8b989e579ab20f2c90135156e665d207ee0aaaab182afff4524c829bR340)

### PR DESCRIPTION
**Pull request by tnobayashi**
## 🔄 Changes Summary
In the enviroment `bali-63-outpost` appears the error `transaction type not supported`. To avoid that we can use `HeaderByNumber` instead of `BlockByNumber`

- replace [BlockByNumber](https://pkg.go.dev/github.com/ethereum/go-ethereum/ethclient#Client.BlockByNumber) by [HeaderByNumber](https://pkg.go.dev/github.com/ethereum/go-ethereum/ethclient#Client.HeaderByNumber)

## ✅ Testing
- 🤖 **Automatic**:

## 🐞 Issues
- Closes #1388

## 🔗 Related PRs
- https://github.com/agglayer/aggkit/pull/1169

### CODE REVIEW

**Review by goran-ethernal — APPROVED** [review]

File: test/helpers/reorg.go [hunk 1]
```diff
@@ -28,8 +28,8 @@ func Reorg(t *testing.T, client *simulated.Backend, reorgSizeInBlocks uint64) {
 	currentBlockNum, err := client.Client().BlockNumber(ctx)
 	require.NoError(t, err)
 
-	block, err := client.Client().BlockByNumber(ctx, big.NewInt(int64(currentBlockNum-reorgSizeInBlocks)))
-	log.Debugf("reorging until block %d. Current block %d (before reorg)", block.NumberU64(), currentBlockNum)
+	block, err := client.Client().HeaderByNumber(ctx, big.NewInt(int64(currentBlockNum-reorgSizeInBlocks)))
+	log.Debugf("reorging until block %d. Current block %d (before reorg)", block.Number.Uint64(), currentBlockNum)
 	require.NoError(t, err)
 	reorgFrom := block.Hash()
```
Comment (Stefan-Ethernal) [inline test/helpers/reorg.go]: Minor nitpick:

```suggestion
	header, err := client.Client().HeaderByNumber(ctx, new(big.Int).SetUint64(currentBlockNum-reorgSizeInBlocks))
	log.Debugf("reorging until block %d. Current block %d (before reorg)", header.Number.Uint64(), currentBlockNum)
	require.NoError(t, err)
	reorgFrom := header.Hash()
```

File: etherman/config/network.go [hunk 2]
```diff
@@ -90,6 +90,7 @@ type RPCMode string
 
 var (
 	RPCModeBasic RPCMode = "basic"
+	RPCModeHash  RPCMode = "hash"
```
Comment (Stefan-Ethernal) [inline etherman/config/network.go]: This value seems not to be used?

```suggestion
```

**Review by Stefan-Ethernal — APPROVED** [review]
LGTM, aside from minor suggestions

File: etherman/config/network.go (hunk 2 above)
Comment (joanestebanr) [reply etherman/config/network.go]: good catch!  bee735d74fd135f3203867b441028a54511b83c6
