### PR TITLE
fix: adapt aggkit (optimistic mode) to aggchainFEP contract

### LINKED ISSUE #1070: fix: adapt aggkit (optimistic mode) to  aggchainFEP contract
# Bug Report
`RollupConfigHash` and `RangeVkeyCommitment` calls are deprecated in favour of `selectedOpSuccinctConfigName()` then get the config `opSuccinctConfigs(name)`
affected versions:  <= `v0.7.0-beta7`

Logs: 
```
[aggkit-prover-001] stderr: called `Result::unwrap()` on an `Err` value: InvalidSigner { declared: Address(0x5b06837a43bdc3dd9f114558daf4b26ed49842ed), recovered: Address(0xf3e80471423800763def192bcfcb194ff8faa1af) }
[aggkit-prover-001] stderr: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Check PR: https://github.com/agglayer/agglayer-contracts/pull/506

### PR DESCRIPTION
**Pull request by joanestebanr**
## 🔄 Changes Summary
- Use aggsanderContract.OpSuccinctConfigs to get `RangeVkeyCommitment` and `RollupConfigHash`

## 🐞 Issues
- Closes #1070

### CODE REVIEW

**Review by goran-ethernal — APPROVED** [review]

File: aggsender/optimistic/interfaces.go [hunk 1]
```diff
@@ -18,9 +18,14 @@ type FEPContractQuerier interface {
 	StartingBlockNumber(opts *bind.CallOpts) (*big.Int, error)
 	LatestBlockNumber(opts *bind.CallOpts) (*big.Int, error)
 	GetAggchainSigners(opts *bind.CallOpts) ([]common.Address, error)
-	RollupConfigHash(opts *bind.CallOpts) ([32]byte, error)
-	RangeVkeyCommitment(opts *bind.CallOpts) ([32]byte, error)
 	OptimisticMode(opts *bind.CallOpts) (bool, error)
+
```
Comment (Stefan-Ethernal) [inline aggsender/optimistic/interfaces.go]: Is there any reason for the empty line here?

```suggestion
```

**Review by Stefan-Ethernal — APPROVED** [review]

File: aggsender/optimistic/interfaces.go (hunk 1 above)
Comment (joanestebanr) [reply aggsender/optimistic/interfaces.go]: No reason!, deleted!
