### PR TITLE
fix: certificate size estimation for `grpc`

### LINKED ISSUE #541: Adapt max size of certs to gRPC
max size logic and config was meant for jRPC, it needs to be adapted to gRPC

### PR DESCRIPTION
**Pull request by goran-ethernal**
## Description

This PR fixes certificate size estimation because we moved to `grpc` communication with `agglayer`, so the sizes changed.

Fixes #541 (issue)

### CODE REVIEW

File: agglayer/types/types.go [hunk 1]
```diff
@@ -28,6 +28,11 @@ const (
 	nilStr  = "nil"
 	nullStr = "null"
 	base10  = 10
+
+	EstimatedAggchainProofSize      = 10_000
```
Comment (Stefan-Ethernal) [inline agglayer/types/types.go]: Is this nominated in bytes? Also, it would probably make sense to introduce constants in the aggkit:

And here we would say `10 * common.KB`

```go
const (
    KB = 1 << 10 // 1024
    MB = 1 << 20 // 1,048,576
    GB = 1 << 30 // 1,073,741,824
)
```

WDYT?

File: agglayer/types/types_test.go [hunk 2]
```diff
@@ -21,7 +21,7 @@ import (
...
...89444f63de0378e3d121be09e06cc9ded1c20e65876d36aa0","0xc65e9645644786b620e2dd2ad648ddfcbf4a7e5b1a3a4ecfe7f64667a3f0b7e2","0xf4418588ed35a2458cffeb39b93d26f18d2ab13bdce6aee58e7b99359ec2dfd9","0x5a9c16dc00d6ef18b7933a6f8dc65ccb55667138776f7dea101070dc8796e377","0x4df84f40ae0c8229d0d6069e5c8f39a7c299677a09d367fc7b05e3bc380ee652","0xcdc72595f74c7b1043d0e1ffbab734648c838dfb0527d971b602bc216c9619ef","0x0abf5ac974a1ed57f4050aa510dd9c74f508277b39d7973bb2dfccc5eeb0618d","0xb8cd74046ff337f0a7bf2c8e03e10f642c1886798d71806ab1e888d9e5ee87d0","0x838c5655cb21c6cb83313b5a631175dff4963772cce9108188b34ac87c81c41e","0x662ee4dd2dd7b2bc707961b1e646c4047669dcb6584f0d8d770daf5d7e7deb2e","0x388ab20e2573d171a88108e79d820e98f26c0b84aa8b2f4aa4968dbb818ea322","0x93237c50ba75ee485f4c22adf2f741400bdf8d6a9cc7df7ecae576221665d735","0x8448818bb4ae4562849e949e17ac16e0be16688e156b5cf15e098c627c0056a9"]}}}},"global_index":{"mainnet_flag":false,"rollup_index":1,"leaf_index":0}}],"metadata":"0x0100000000000000010000007667d2df67000000000000000000000000000000","aggchain_data":{"signature":"59e46153ce34143f3b9cc3786f2473d8aa80ba578f07102d59ad01cbf221f81b4a9d68f0edc5635df585c134486b465bd588cd7f76a4d7154ba81e299f8f7ed601"}}`
```
Comment (Stefan-Ethernal) [inline agglayer/types/types_test.go:24]: Nitpick, wdyt if we have a separate file that holds test certificates, so we can run different test vectors against the same tests?

As a side note, there is a Println leftover [here](https://github.com/agglayer/aggkit/blob/de662c7ea6f2450f833a8ad960e8e8f4e22629ba/agglayer/types/types_test.go#L907).

File: agglayer/grpc/agglayer_grpc_client_test.go [hunk 3]
```diff
@@ -526,3 +530,49 @@ func TestCertificateStatusFromProto(t *testing.T) {
...
+	require.NoError(t, err)
+
+	aggchainSigData := &v1types.AggchainData{
+		Data: &v1types.AggchainData_Signature{
+			Signature: &v1types.FixedBytes65{Value: sig},
+		},
+	}
+	size = estimateRequestSize(t, aggchainSigData)
+	fmt.Printf("aggchain data signature size: %d bytes\n", size)
+}
```
Comment (Stefan-Ethernal) [inline agglayer/grpc/agglayer_grpc_client_test.go]: Is this some kind of exploratory test? If yes, probably skip it, otherwise, it makes sense to add some assertions on the sizes. WDYT?

**Review by Stefan-Ethernal — APPROVED** [review]

File: agglayer/grpc/agglayer_grpc_client_test.go (hunk 3 above)
Comment (goran-ethernal) [reply agglayer/grpc/agglayer_grpc_client_test.go]: Fix: https://github.com/agglayer/aggkit/pull/564/commits/198615a2d00c79375e7a325904d8bc157fdaa715

File: agglayer/types/types.go (hunk 1 above)
Comment (goran-ethernal) [reply agglayer/types/types.go]: Fix: https://github.com/agglayer/aggkit/pull/564/commits/198615a2d00c79375e7a325904d8bc157fdaa715

File: agglayer/types/types_test.go (hunk 2 above)
Comment (goran-ethernal) [reply agglayer/types/types_test.go:24]: Fix for the leftover: https://github.com/agglayer/aggkit/pull/564/commits/198615a2d00c79375e7a325904d8bc157fdaa715

As for the separation to different files, I would like to address this in another PR. I was planning to restructure the UTs a bit on aggsender, to introduce some test vectors in a form of JSON files through this issue: https://github.com/agglayer/aggkit/issues/565

**Review by joanestebanr — APPROVED** [review]
