### PR TITLE
fix: FEP cert validation

### LINKED ISSUE #1025: fix local Validator for FEP
# Bug Report
Version: `v0.7.0-beta3`

Remote validator fails: 
```
[aggkit-001-aggsender-validator-002] {"level":"error","ts":1758187308.792973,"caller":"validator/validator_service.go:103","msg":"Certificate validation failed: failed to validate last L2 block in new certificate: failed to get new certificate to block: failed to resolve the block number for last imported bridge exit MainnetFlag: true, RollupIndex: 0, LeafIndex: 1: no claim found for bridge exit hash 0x687a68bb02c123f1f71c4eb8f8861357ecc4e420922226563b4772e5d772acef","pid":7,"version":"","module":"aggsender-validator","stacktrace":"github.com/agglayer/aggkit/aggsender/validator.(*ValidatorService).ValidateCertificate\n\t/app/aggsender/validator/validator_service.go:103\ngithub.com/agglayer/aggkit/aggsender/validator/proto/v1._AggsenderValidator_ValidateCertificate_Handler\n\t/app/aggsender/validator/proto/v1/validator_grpc.pb.go:121\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.75.0/server.go:1431\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.75.0/server.go:1842\ngoogle.golang.org/grpc.(*Server).serveStreams.func2.1\n\t/go/pkg/mod/google.golang.org/grpc@v1.75.0/server.go:1061"}
```

The FEP certificate fail checking locally because aggchainData doesn't match

```
[aggkit-001] {"level":"error","ts":1758184186.1112525,"caller":"validator/local_validator.go:93","msg":"certificate validation failed: certificate not equal to expected: certificates mismatch. FullDiff: CustomChainData mismatch. Expected: 00060001000000000000000000000000000000000000000000000000000000001bab55cb7ff9e6f5a3acd6f780704f3d091c743d05f17d89afc0d7c3a13a8fb3000000000000000000000000000000000000000000000000000000000000003d, Certificate: . Cert: agglayer.Cert {height: 0 prevLER: 0x27ae5ba08d7291c96c8cbddcc148bf48a6d68c7974b94356f53754ef6171d757, newLER: 0x27ae5ba08d7291c96c8cbddcc148bf48a6d68c7974b94356f53754ef6171d757, exits: 0 imported_exits: 0}","pid":7,"version":"","module":"aggsender","stacktrace":"github.com/agglayer/aggkit/aggsender/validator.(*LocalValidator).ValidateAndSignCertificate\n\t/app/aggsender/validator/local_validator.go:93\ngithub.com/agglayer/aggkit/aggsender.(*AggSender).sendCertificate\n\t/app/aggsender/aggsender.go:338\ngithub.com/agglayer/aggkit/aggsender.(*AggSender).sendCertificateWithRetries.func1\n\t/app/aggsender/aggsender.go:301\ngithub.com/agglayer/aggkit/common.Execute[...]\n\t/app/common/retry_handler_delays.go:131\ngithub.com/agglayer/aggkit/aggsender.(*AggSender).sendCertificateWithRetries\n\t/app/aggsender/aggsender.go:296\ngithub.com/agglayer/aggkit/aggsender.(*AggSender).sendCertificates\n\t/app/aggsender/aggsender.go:270\ngithub.com/agglayer/aggkit/aggsender.(*AggSender).Start\n\t/app/aggsender/aggsender.go:203"}
[aggkit-001] {"level":"error","ts":1758184186.1113276,"caller":"aggsender/aggsender.go:339","msg":"error validating certificate locally: %!w(*fmt.wrapError=&{certificate validation failed: certificate not equal to expected: certificates mismatch. FullDiff: CustomChainData mismatch. Expected: 00060001000000000000000000000000000000000000000000000000000000001bab55cb7ff9e6f5a3acd6f780704f3d091c743d05f17d89afc0d7c3a13a8fb3000000000000000000000000000000000000000000000000000000000000003d, Certificate:  0xc000591700})","pid":7,"version":"","module":"aggsender","stacktrace":"github.com/agglayer/aggkit/aggsender.(*AggSender).sendCertificate\n\t/app/aggsender/aggsender.go:339\ngithub.com/agglayer/aggkit/aggsender.(*AggSender).sendCertificateWithRetries.func1\n\t/app/aggsender/aggsender.go:301\ngithub.com/agglayer/aggkit/common.Execute[...]\n\t/app/common/retry_handler_delays.go:131\ngithub.com/agglayer/aggkit/aggsender.(*AggSender).sendCertificateWithRetries\n\t/app/aggsender/aggsender.go:296\ngithub.com/agglayer/aggkit/aggsender.(*AggSender).sendCertificates\n\t/app/aggsender/aggsender.go:270\ngithub.com/agglayer/aggkit/aggsender.(*AggSender).Start\n\t/app/aggsender/aggsender.go:203"}


``

### PR DESCRIPTION
**Pull request by joanestebanr**
## 🔄 Changes Summary
- The validator doesn't generate the aggchain proof, so the field `CustomChainData` is not possible to be compare

## 🐞 Issues
- Closes #1025

### CODE REVIEW

File: aggsender/validator/compare_certs.go [hunk 1]
```diff
@@ -39,11 +38,6 @@ func DiffsCertificate(
 			expectedCertificate.NewLocalExitRoot.Hex(), validatingCertificate.NewLocalExitRoot.Hex()))
 	}
 
-	if !bytes.Equal(validatingCertificate.CustomChainData, expectedCertificate.CustomChainData) {
-		diffs = append(diffs, fmt.Sprintf("CustomChainData mismatch. Expected: %x, Certificate: %x",
-			expectedCertificate.CustomChainData, validatingCertificate.CustomChainData))
-	}
```
Comment (Stefan-Ethernal) [inline aggsender/validator/compare_certs.go:45]: We don't need this validation afterwards, or this is temporary until some issue gets fixed on the agglayer?

Comment (joanestebanr) [reply aggsender/validator/compare_certs.go:45]: Good question: we have to think about it,  validator are no generating a aggchain proof  so we can't compare with the one generated locally. By other hand maybe make sense to to verify it in the same way that as agglayer do  for a fail fast

**Review by Stefan-Ethernal — APPROVED** [review]
LGTM (at least for now, until we figure out if we can somehow validate the `CustomChainData`)
